
[font]
size = 12

[general]
import = ["~/.config/alacritty/themes/gruvbox-material-alacritty.toml"]

[terminal]

[terminal.shell]
program = "/usr/bin/zellij"

[window]
opacity = 0.7
# decoration = "none"
