import {IIndexing} from 'wlc-engine/interfaces';

export const files: IIndexing<string> = {
    'defaultLogo': 'default-logo.svg',
    'defaultFooterLogo': 'default-logo.svg',

    /* merchants */
    'amatic': 'merchants/amatic.svg',
    'amaticdirect': 'merchants/amaticdirect.svg',
    'apollo': 'merchants/apollo.svg',
    'asiagaming': 'merchants/asiagaming.svg',
    'asialivetech': 'merchants/asialivetech.svg',
    'authenticgaming': 'merchants/authenticgaming.svg',
    'betconstruct': 'merchants/betconstruct.svg',
    'betgames': 'merchants/betgames.svg',
    'betradar': 'merchants/betradar.svg',
    'betsoft': 'merchants/betsoft.svg',
    'boominggames': 'merchants/boominggames.svg',
    'digitain': 'merchants/digitain.svg',
    'egtinteractive': 'merchants/egtinteractive.svg',
    'endorphina': 'merchants/merchants/endorphina.svg',
    'evolution': 'merchants/evolution.svg',
    'evoplay': 'merchants/evoplay.svg',
    'extremelive': 'merchants/extremelive.svg',
    'ezugi': 'merchants/ezugi.svg',
    'gameart': 'merchants/gameart.svg',
    'ggnetwork': 'merchants/ggnetwork.svg',
    'goldenrace': 'merchants/goldenrace.svg',
    'habanero': 'merchants/habanero.svg',
    'isoftbet': 'merchants/isoftbet.svg',
    'kiron': 'merchants/kiron.svg',
    'luckystreak': 'merchants/luckystreak.svg',
    'microgaming': 'merchants/microgaming.svg',
    'mrslotty': 'merchants/mrslotty.svg',
    'netent': 'merchants/netent.svg',
    'onextwonetwork': 'merchants/onextwonetwork.svg',
    'orientalgame': 'merchants/orientalgame.svg',
    'pariplay': 'merchants/pariplay.svg',
    'patagonia': 'merchants/patagonia.svg',
    'platipus': 'merchants/platipus.svg',
    'playngo': 'merchants/playngo.svg',
    'playson': 'merchants/playson.svg',
    'playsondirect': 'merchants/playsondirect.svg',
    'pragmatic': 'merchants/pragmatic.svg',
    'pragmaticplay': 'merchants/pragmaticplay.svg',
    'quickspin': 'merchants/quickspin.svg',
    'sagaming': 'merchants/sagaming.svg',
    'spigo': 'merchants/spigo.svg',
    'spinomenal': 'merchants/spinomenal.svg',
    'spotoption': 'merchants/spotoption.svg',
    'stakelogic': 'merchants/stakelogic.svg',
    'tomhorn': 'merchants/tomhorn.svg',
    'vivogaming': 'merchants/vivogaming.svg',
    'wacs': 'merchants/wacs.svg',
    'wazdan': 'merchants/wazdan.svg',
    'worldmatch': 'merchants/worldmatch.svg',
    'yggdrasil': 'merchants/yggdrasil.svg',

    /*payments*/
    'ecopayz': 'payments/ecopayz.svg',
    'neteller': 'payments/neteller.svg',
    'paycryptos_bitcoin': 'payments/paycryptos_bitcoin.svg',
    'paycryptos_ethereum': 'payments/paycryptos_ethereum.svg',
    'paycryptos_litecoin': 'payments/paycryptos_litecoin.svg',
    'paymentiq_interac': 'payments/paymentiq_interac.svg',
    'skrill': 'payments/skrill.svg',
    'wirecard': 'payments/wirecard.svg',
    'yandexmoney': 'payments/yandexmoney.svg',
};
