image: dockerproxy.egamings.com:443/chromium-node:14

stages:
    - checks

# default:
#     cache:
#         paths:
#             - node_modules/

before_script:
    - source ~/.bashrc
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa wlcgitlab.egamings.com >> ~/.ssh/known_hosts
    - git submodule update --init
    - PACKAGE_HASH=($(md5sum package-lock.json))
    - DEPS_CACHE=/builds/deps_${PACKAGE_HASH}.tgz
    - if [ -f ${DEPS_CACHE} ]; then tar -xf ${DEPS_CACHE}; else npm ci; tar -czf ${DEPS_CACHE} ./node_modules; fi

run_checks:
    stage: checks
    script:
        - npx concurrently --names "changes,eslint,stylelint,test,compodoc,sassdoc" "npm run checking-changes" "npm run eslint" "npm run stylelint" "npm run test" "npm run build:docs" "npm run build:sassdocs"
        - echo "Job end at $(date +%H:%M:%S)"
    only:
        - merge_requests
