image: dockerproxy.egamings.com/chromium-node:18

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - checks

cache:
    key: ${CI_PROJECT_PATH_SLUG}
    paths:
        - node_modules/
        - .angular/

before_script:
    - source ~/.bashrc
    - cp ${NPMRC} ~/.npmrc
    - npm install --cache .npm --prefer-offline

checking-changes:
    stage: checks
    script:
        - npm run checking-changes

eslint:
    stage: checks
    script:
        - npm run eslint

stylelint:
    stage: checks
    script:
        - npm run stylelint

test:
    stage: checks
    script:
        - npm run test

docs:
    stage: checks
    script:
        - npm run build:docs

sassdocs:
    stage: checks
    script:
        - npm run build:sassdocs
