export const crossDomainEvents = {
    AUTH: 'JWT_AUTH',
    AUTH_UPDATE: 'JWT_AUTH_UPDATE',
    AUTH_LOGIN: 'JWT_AUTH_LOGIN',
    AUTH_LOGOUT: 'JWT_AUTH_LOGOUT',
    SET_TOKENS: 'JWT_SET_TOKENS',
    XNONCE_UPDATE: 'XNONCE_UPDATE',
    GET_TOKENS: 'JWT_GET_TOKENS',
    AUTH_SYNC: 'JWT_AUTH_SYNC',
} as const;
