import {IIndexing} from 'wlc-engine/modules/core/system/interfaces';

export const localFiles: IIndexing<string> = {
    'status/ok': 'icons/status/ok.svg',
    'status/alert': 'icons/status/alert.svg',
    'status/confirm': 'icons/status/confirm.svg',
    'defaultLogo': 'icons/default-logo.svg',
    'defaultFooterLogo': 'icons/default-logo.svg',
    '404-error': 'icons/404-error.svg',
    'poweroff': 'icons/poweroff.svg',
    'loading': 'icons/loading.svg',
    'arrow': 'icons/arrow.svg',
    'thin-arrow': 'icons/thin-arrow.svg',
    'fullscreen': 'icons/fullscreen.svg',
    'close': 'icons/close.svg',
    'favourite':'icons/favourite.svg',
    'eye': 'icons/eye.svg',
    'tick': 'icons/tick.svg',
    'clock': 'icons/clock.svg',
    'search': 'icons/search.svg',
    'filter-merchants': 'icons/filter-merchants.svg',
    'filter-categories': 'icons/filter-categories.svg',
    'age-restrictions': 'icons/age-restrictions.svg',
    'info': 'icons/info.svg',
    'burger': 'icons/burger.svg',
    'winner-arrow': 'decors/winner-arrow.svg',
    'calendar': 'icons/calendar.svg',
    'login': 'icons/login.svg',
    'user-icon': 'icons/user-icon.svg',
    'logout': 'icons/logout.svg',
    'settings': 'icons/settings.svg',
    'game-dashboard/profile': 'game-dashboard/profile.svg',
    'game-dashboard/bonuses': 'game-dashboard/bonuses.svg',
    'game-dashboard/last-played': 'game-dashboard/last-played.svg',
    'game-dashboard/tournaments': 'game-dashboard/tournaments.svg',
    'game-dashboard/arrow-right': 'game-dashboard/arrow-right.svg',
    'check': 'icons/check.svg',
    'game-thumb-play': 'icons/games/game-thumb-play.svg',
    'enter-arrow': 'icons/enter-arrow.svg',
    'promo-success': 'decors/promo-success.svg',
    'copy': 'icons/copy.svg',
    'doc-common': 'icons/doc-icons/doc.svg',
    'doc-1': 'icons/doc-icons/personal.svg',
    'doc-2': 'icons/doc-icons/personal.svg',
    'doc-3': 'icons/doc-icons/personal.svg',
    'doc-4': 'icons/doc-icons/payment.svg',
    'doc-5': 'icons/doc-icons/address.svg',
    'awaiting-validation': 'icons/doc-icons/pending.svg',
    'validated': 'icons/doc-icons/loaded.svg',
    'failed-validation': 'icons/doc-icons/not-correct.svg',
    'question-mark': 'icons/question-mark.svg',
    'defCategoryIcon': 'icons/plug.svg',
    'pool': 'icons/pool.svg',
    'cup': 'icons/cup.svg',
};
