import {IIndexing} from 'wlc-engine/modules/core/system/interfaces';

export const localFiles: IIndexing<string> = {
    'defaultLogo': 'icons/default-logo.svg',
    'defaultFooterLogo': 'icons/default-logo.svg',
    '404-error': 'icons/404-error.svg',
    'poweroff': 'icons/poweroff.svg',
    'loading': 'icons/loading.svg',
    'arrow': 'icons/arrow.svg',
    'thin-arrow': 'icons/thin-arrow.svg',
    'fullscreen': 'icons/fullscreen.svg',
    'close': 'icons/close.svg',
    'favourite':'icons/favourite.svg',
    'eye': 'icons/eye.svg',
    'tick': 'icons/tick.svg',
    'search': 'icons/search.svg',
    'filter-merchants': 'icons/filter-merchants.svg',
    'filter-categories': 'icons/filter-categories.svg',
    'age-restrictions': 'icons/age-restrictions.svg',
    'info': 'icons/info.svg',
    'burger': 'icons/burger.svg',
    'winner-arrow': 'decors/winner-arrow.svg',
    'calendar': 'icons/calendar.svg',
    'login': 'icons/login.svg',
    'user-icon': 'icons/user-icon.svg',
    'logout': 'icons/logout.svg',
    'game-dashboard/profile': 'game-dashboard/profile.svg',
    'game-dashboard/bonuses': 'game-dashboard/bonuses.svg',
    'game-dashboard/last-played': 'game-dashboard/last-played.svg',
    'game-dashboard/tournaments': 'game-dashboard/tournaments.svg',
    'game-dashboard/arrow-right': 'game-dashboard/arrow-right.svg',
    'check': 'icons/check.svg',
    'game-thumb-play': 'icons/games/game-thumb-play.svg',
    'enter-arrow': 'icons/enter-arrow.svg',
};
