import {
    CustomType,
    IComponentParams,
    ILinkBlockCParams,
} from 'wlc-engine/modules/core';

export type Type = 'default' | CustomType;
export type Theme = 'default' | CustomType;
export type ThemeMod = 'default' | CustomType;

export interface ITwoFactorAuthInfoCParams extends IComponentParams<Theme, Type, ThemeMod> {
    title?: string;
    subtitle?: string;
    description?: string;
    linkBlockParams?: ILinkBlockCParams;
    iconPath?: {
        appStore?: string,
        googlePlay?: string,
    }
}

export const defaultParams: ITwoFactorAuthInfoCParams = {
    moduleName: 'two-factor-auth',
    componentName: 'wlc-two-factor-auth-info',
    class: 'wlc-two-factor-auth-info',
    title: gettext('Google Authenticator'),
    subtitle: gettext('Download and install the Authenticator app'),
    description: gettext(
        'After connecting Google Authenticator, you will be prompted ' +
        'to enter the current code generated by the application when ' +
        'logging into your account. This additional layer of security helps ' +
        'protect your account from unauthorized access.',
    ),
    linkBlockParams: {
        common: {
            subtitle: gettext('Don\'t want to see this message again?'),
            link: gettext('Turn off'),
            actionParams: {
                event: {
                    name: 'TURN_OFF_NOTIFICATION',
                },
            },
        },
    },
    iconPath: {
        appStore: '/wlc/icons/app_store-logo.svg',
        googlePlay: '/wlc/icons/google_play-logo.svg',
    },
};
