import {IPaymentSystem} from 'wlc-engine/modules/finances/system/models/payment-system.model';

export const cryptoInvoiceSystem: Readonly<IPaymentSystem> = {
    id: '-1',
    alias: 'paycryptos_invoices',
    name: gettext('PayCryptos via Invoices'),
    disable_amount: false,
    showfor: 'Deposits',
    appearance: 'replace',
    allowiframe: 0,
    additional: '',
    additionalParams: [],
    description: '',
    image: '',
    lastAccounts: [],
    message: '',
    required: [],
    required_withdraw: [],
    hostedFields: [],
    default_images: ['image', 'image_withdraw'],
};


export const aliasTickerMap = {
    paycryptos_bitcoin: 'BTC',
    paycryptos_bitcoin_v2: 'BTC',
    paycryptos_bitcoincash: 'BCH',
    paycryptos_bitcoincash_v2: 'BCH',
    paycryptos_dogecoin: 'DOGE',
    paycryptos_dogecoin_v2: 'DOGE',
    paycryptos_elrond: 'EGLD',
    paycryptos_elrond_v2: 'EGLD',
    paycryptos_eos: 'EOS',
    paycryptos_ethereum: 'ETH',
    paycryptos_ethereum_v2: 'ETH',
    paycryptos_ethereum_doppel: 'ETH',
    paycryptos_litecoin: 'LTC',
    paycryptos_litecoin_v2: 'LTC',
    paycryptos_ripple: 'XRP',
    paycryptos_ripple_v2: 'XRP',
    paycryptos_tether: 'USDT',
    paycryptos_tether_v2: 'USDT',
    paycryptos_tether__tron_: 'USDT',
    paycryptos_tether__tron__v2: 'USDT',
    paycryptos_tron: 'TRX',
    paycryptos_tron_v2: 'TRX',
    paycryptos_usdt: 'USDT',
    paycryptos_usdt_v2: 'USDT',
    paycryptos_usdt__tron_: 'USDT',
    paycryptos_usdt__tron__v2: 'USDT',
    paycryptos_gdx: 'GDX',
    paycryptos_bnb: 'BNB',
    paycryptos_bseth: 'BSETH',
    paycryptos_busdt: 'BUSDT',
} as const;
