export {IBannerCParams} from './banner/banner.params';
export {IBannersSliderCParams} from './banners-slider/banners-slider.params';
export {ISliderCParams, ISlide} from './slider/slider.params';
export {IWinnerCParams} from './winner/winner.params';
export {IWinnersSliderCParams} from './winners-slider/winners-slider.params';
export {JackpotComponent} from './jackpot/jackpot.component';
export {WinnerComponent} from './winner/winner.component';
export {SliderComponent} from './slider/slider.component';
export {JackpotsSliderComponent} from './jackpots-slider/jackpots-slider.component';
export {WinnersSliderComponent} from './winners-slider/winners-slider.component';
export {LoyaltyProgramComponent} from './loyalty-program/loyalty-program.component';
export {LoyaltyLevelsComponent} from './loyalty-levels/loyalty-levels.component';
export {LoyaltyInfoComponent} from './loyalty-info/loyalty-info.component';
export {BannersSliderComponent} from './banners-slider/banners-slider.component';
export {BannerComponent} from './banner/banner.component';
