#!/bin/bash
#

# Test message for correct formatting
function run_messagecheck
{
    # Prevent commit to the wrong branch
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    if ! [[ "$current_branch" =~ scr[0-9]+(-[0-9]+)? ]]; then
      exit 0
    fi

    ticket_number=$(grep -Poi "(?<=scr)[^-]+(?=[-.*]*)" <<< $current_branch)

    commit_message=$(head -n1 $1)

    regExp="^SCR #$ticket_number - (major|BREAKING CHANGE|minor|feat|patch|fix|docs|test|refactor):.+";

    if ! [[ "$commit_message" =~ $regExp ]]; then
        echo -e "\n\e[5m\e[1m\e[91mBad commit message\e[25m\e[0m"
        echo -e "The commit-message should contain the number of ticket corresponding branch and type prefix"
        echo -e "Current branch is \e[1m\e[93m$current_branch\e[0m"
        echo -e "See example: \e[1m\e[92mSCR #$ticket_number - feat:subject of the ticket\e[0m\n"
        echo -e "More details: \n - https://wiki.egamings.com/display/GS/Tasks+workflow\n - https://www.conventionalcommits.org/en/v1.0.0/\n"
        exit 1;
    fi
}

case "${1}" in
    --about )
        echo -n "Checks for correct commit message format."
        ;;
    * )
        run_messagecheck "$@"
        ;;
esac
