[[mgr.prepend_keymap]]
on   = [ "g", "h" ]
run  = "cd ~"
desc = "Cd to home"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Projects"
desc = "Cd to ~/Projects"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/Projects/src/wlc-engine"
desc = "Cd to wlc-engine"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "Cd to .config"


[[mgr.prepend_keymap]]
on   = [ "o", "g" ]
run  = "lazygit"
desc = "Open lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "e"]
run  = "shell --block hx"
desc = "Open helix"

## TODO interactive start just commands
# [[manager.prepend_keymap]]
# on   = [ "g", "e"]
# run  = "shell --block just"
# desc = "Open helix"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = ["~"]
run = "plugin simple-tag -- toggle-tag"
desc = "Toggle tag"

[[manager.prepend_keymap]]
on = ["T","s"]
run = "plugin simple-tag -- toggle-select"
desc = "Filter by tag"

[[manager.prepend_keymap]]
on = ["T","c"]
run = "plugin simple-tag -- clear"
desc = "Clear all tags"

